addComment/urls.py
from django.conf.urls import url

from .import views

app_name = 'addComment'
urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^createComment/$',views.createComment,name='createComment'),
	url(r'^loadComments/$',views.loadComments,name='loadComments'),
	url(r'^deleteComment/$',views.deleteComment,name='deleteComment'),
	url(r'^login/$',views.login,name='login'),
]

comments/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^addComment/', include('addComment.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url('^accounts/',include('django.contrib.auth.urls')),
]

polls/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'polls'

urlpatterns = [
	url(r'^$', views.PollsList.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.PollDetail.as_view(), name='detail'),
	url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
	url('^', include('django.contrib.auth.urls')),
	url(r'^myPolls/$',views.userPolls.as_view(),name='userPolls'),
	url(r'myPolls/add/$', views.createPoll, name='createPoll'),
	url(r'^signUp/$',views.registration.as_view(),name='registerUser'),
	url(r'^test/$',views.test,name='test'),
]

addComment/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.conf import settings
from django.db import models

# Create your models here.
class Comments(models.Model):
	comment = models.CharField(max_length=250)
	pub_date = models.DateTimeField('date published')


	def __str__(self):
		return self.comment

polls/models.py
from __future__ import unicode_literals
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Question(models.Model):
	poster = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
	question = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def get_absolute_url(self):
		return reverse('Question-detail', kwargs={'pk': self.pk})

	def __str__(self):
		return self.question



class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice

addComment/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
class loginForm(AuthenticationForm):
	pass


class createAccount(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username','email','password')

polls/forms.py
from django.forms import ModelForm, Textarea, CharField, BaseFormSet
from polls.models import Question, Choice
from django.contrib.auth.models import User
from django import forms

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['question']


class ChoiceForm(forms.ModelForm):
	class Meta:
		model = Choice
		fields = ['choice']


class registrationForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username','email','password']

addComment/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.urls import reverse
from .models import Comments
from django.core import serializers 
from django.contrib.auth import authenticate, login, logout
from .forms import loginForm, createAccount
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def index(request):
	return render (request, 'addComment/index.html')



def deleteComment(request):
	Comments.objects.filter(id=request.POST['delComment']).delete()
	comments = Comments.objects.all()

	return render(request,'addComment/comments.html',{'comments':comments})


def createComment(request):
	if request.method == "POST":
		q = Comments(comment = request.POST['comment'],pub_date = timezone.now())
		q.save()


	return HttpResponse(serializers.serialize("json",Comments.objects.filter(pk=q.pk)))


def loadComments(request):
	comments = serializers.serialize("json",Comments.objects.order_by('-pk'))
	return HttpResponse(comments)



def login(request):
	if request.method == 'POST':
		form = createAccount(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']

			user = User.objects.create_user(username,email,password)
			auth.login(request,user)
			return redirect('addComment:index')
				
	else:
		form = createAccount()

	return render(request, 'addComment/login.html',{'form':form})

polls/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView, View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import auth
from django.utils import timezone
from .models import Question, Choice
from polls.forms import QuestionForm, ChoiceForm, registrationForm
from django.forms import formset_factory, inlineformset_factory, modelformset_factory
# Create your views here.

class PollsList(ListView):
	model = Question

class PollDetail(DetailView):
	model = Question
	template_name = 'polls/choices.html'


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	selected_choice = question.choice_set.get(id=request.POST['choice'])

	selected_choice.votes += 1
	selected_choice.save()
	return HttpResponse(selected_choice.votes)

def test(request):
	pass


class registration(View):
	form_class = registrationForm
	template_name = 'polls/registration.html'

	def get(self,request):
		form = self.form_class(None)
		return render(request,self.template_name,{'form':form})

	def post(self,request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			user.set_password(password)
			user.save()

			user = authenticate(username=username,email=email,password=password)

			if user is not None:
				if user.is_active:
					auth.login(request,user)
					return redirect('polls:index')

		return render(request,self.template_name,{'form':form})



class userPolls(ListView, LoginRequiredMixin):

	template_name = 'polls/userPolls.html'
	
	def get_queryset(self):
		self.user = get_object_or_404(User, username=self.request.user)
		return self.user.question_set.all()

@login_required
def createPoll(request):

	pollFormSet = formset_factory(ChoiceForm, extra = 2, max_num = 6)
	if request.method == 'POST':
		form = QuestionForm(request.POST)
		formset = pollFormSet(request.POST, request.FILES)
		if form.is_valid() and formset.is_valid():
			question = form.save(commit=False)
			question.poster = request.user
			question.pub_date = timezone.now()
			question.save()

			for form in formset:
				choice = Choice(choice=form.save(commit=False))
				choice.question = Question.objects.get(pk=question.id)
				choice.save()


		return redirect('polls:index')
	else:
		form = QuestionForm()
		formset = pollFormSet()

	return render(request, 'polls/create_poll.html', {'questionForm':form, 'choiceFormset':formset})




	

addComment/templates/addComment/comments.html
<h1>Comments Posted</h1>
<form action="{% url 'addComment:deleteComment' %}" method="post">
{% csrf_token %}
{% if comments %}
    {% for i in comments %}
        <li><input type="checkbox" name="delComment" value="{{i.id}}">{{ i.comment}}</li>
    {% endfor %}   
{% else %}
    <p>No Comments are available.</p>
{% endif %}
<input type="submit" name="del" value="delete">
</form>

addComment/templates/addComment/index.html
<body>
<form id="commentForm">
	<textarea name="comment" rows="10" cols="30" maxlength="250" required id="comment"></textarea>
	<br>
	<input type="submit" name="action" value="Comment">
</form>
<button id="loadComments">Load Comments</button>
<br>
<div>
	<ul id="Comments">
	</ul>
</div>
</body>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
<script>
var csrftoken = $.cookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


$('#commentForm').submit(function(e){
	e.preventDefault();
  	$.ajax({
  		url: 'createComment/',
  		type: 'POST',
  		data:{
  			comment: document.getElementById("comment").value
  		},
  		success: function(data){
  			obj = JSON.parse(data)
  			$('#Comments').prepend('<li>'+obj[0].fields.comment+'</li>');
  		},
  	});
});

$(document).ready(function(){
    $("#loadComments").click(function(e) {
    	$.get('loadComments/', function(data){
    		obj = JSON.parse(data) //add try catch
    		var comments = "";
    		for(var i=0;i<obj.length;i++){
  				comments += '<li>'+obj[i].fields.comment+'</li>';
  			}
  			$('#Comments').html(comments);
    	});

    	$("#loadComments").hide();
 });


});



</script>

addComment/templates/addComment/loadComments.html
<h1>Comments Posted</h1>
<form action="" method="post">
{% csrf_token %}
{% if comments %}
    {% for i in comments %}
        <li><input type="checkbox" name="delComment" value="{{i.id}}">{{ i.comment}}</li>
    {% endfor %}   
{% else %}
    <p>No Comments are available.</p>
{% endif %}
<input type="submit" name="del" value="delete">
</form>

addComment/templates/addComment/login.html
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

polls/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title></title>
  {% load staticfiles %}
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<header>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'polls:index' %}">VoteMesh</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'polls:index' %}">Home</a></li>
      {% if user.is_authenticated %}
        <li><a href="{%url 'polls:userPolls' %}">My Polls</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li><a href="#"><span class="glyphicon glyphicon-user"></span>{{user.username}}</a></li>
         <li><a href="{% url 'polls:logout' %}"><span class="glyphicon glyphicon-log-in"></span> Logout</a></li>
      {% else %}
        <li><a href="{% url 'polls:registerUser' %}"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
        <li><a href="{% url 'polls:login' %}?next={{request.path}}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
</header>
{% block content%}
{% endblock%}
</body>
</html>

polls/templates/polls/choices.html
{% extends 'base.html' %}
<h1>{{ question.question}}</h1>
{% block content %}
<form id="voteForm">
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" value="{{choice.id}}"> {{choice.choice}} -- <span id="{{choice.id}}">{{choice.votes}}</span><br>
	{% endfor %}
	<br>
<input type="submit" name="vote" value="Vote">
</form>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>


<script>
var csrftoken = $.cookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});


$('#voteForm').submit(function(e){
	e.preventDefault();
  		$.ajax({
  			url: "{% url 'polls:vote' question.id %}",
  			type: 'POST',
  			data:{
  				choice: $('input:checked').val()
  			},
  			success: function(data){
  				changeSpan(data);
  			},
  	});
});


function changeSpan(data) {
	var id = $('input:checked').val();
	$('#' + id).html(data);
}

</script>
{% endblock %}

polls/templates/polls/create_poll.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
<form method="POST" action="">
{% csrf_token %}
    {{questionForm.as_p}}

    {{choiceFormset.management_form}}
<div id="allForm">
    {% for form in choiceFormset %}
        {{form.as_p}}
    {% endfor %}
</div>
<input type="button" value="addChoice" id="add_more">
<input type="submit" name="submit">
</form>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js"></script>
<script>
    $(document).ready(function() {
        // body...
        $('#add_more').click(function(){
            cloneMore('div p:last','form')
        });
    });

    function cloneMore(selector,type) {
        // body...
    var newElement = $(selector).clone(true);
    var total = $('#id_' + type + '-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    total++;
    $('#id_' + type + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    }
</script>
{% endblock %}

polls/templates/polls/question_list.html
{% extends 'base.html' %}

{% block content %}
<h1>All polls</h1>
<ul>
	{% for poll in object_list %}
		<li><a href="{% url 'polls:detail' poll.id %}">{{poll.question}}</a> {{poll.poster}}</li>
	{% endfor %}
</ul>
{% endblock %}

polls/templates/polls/registration.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" action="">
{% csrf_token %}
	{{form.as_p}}

<input type="submit" value="Sign Up">
</form>
{% endblock %}

polls/templates/polls/userPolls.html
{% extends 'base.html' %}

{% block content %}
<ul>
	{% for question in object_list %}
		<li><a href="{}">{{question.question}}</a></li>
	{% endfor %}
</ul>
{% endblock %}